import { University, LoanOffer } from './types'

export const UNIVERSITIES: University[] = [
  // Top Tier - High ECP Required
  {
    id: 'harvard',
    name: 'Harvard University',
    country: 'USA',
    ranking: 1,
    avgFees: 60000,
    program: 'Computer Science',
    fundingAvailable: 'Full',
    cutoffCGPA: 3.8,
    cutoffECP: 80,
  },
  {
    id: 'stanford',
    name: 'Stanford University',
    country: 'USA',
    ranking: 2,
    avgFees: 58000,
    program: 'Engineering',
    fundingAvailable: 'Full',
    cutoffCGPA: 3.9,
    cutoffECP: 85,
  },
  {
    id: 'mit',
    name: 'MIT',
    country: 'USA',
    ranking: 3,
    avgFees: 62000,
    program: 'Engineering & CS',
    fundingAvailable: 'Full',
    cutoffCGPA: 3.85,
    cutoffECP: 82,
  },
  {
    id: 'oxforduni',
    name: 'University of Oxford',
    country: 'UK',
    ranking: 4,
    avgFees: 45000,
    program: 'Finance & Economics',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.7,
    cutoffECP: 78,
  },
  {
    id: 'cambridge',
    name: 'University of Cambridge',
    country: 'UK',
    ranking: 5,
    avgFees: 48000,
    program: 'Mathematics & CS',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.75,
    cutoffECP: 80,
  },

  // Mid Tier - Medium-High ECP Required
  {
    id: 'cmu',
    name: 'Carnegie Mellon University',
    country: 'USA',
    ranking: 6,
    avgFees: 59000,
    program: 'Computer Science',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.7,
    cutoffECP: 72,
  },
  {
    id: 'caltech',
    name: 'Caltech',
    country: 'USA',
    ranking: 7,
    avgFees: 61000,
    program: 'Physics & Engineering',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.8,
    cutoffECP: 75,
  },
  {
    id: 'berkeley',
    name: 'UC Berkeley',
    country: 'USA',
    ranking: 8,
    avgFees: 52000,
    program: 'Engineering & CS',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.6,
    cutoffECP: 68,
  },
  {
    id: 'imperial',
    name: 'Imperial College London',
    country: 'UK',
    ranking: 9,
    avgFees: 44000,
    program: 'Engineering',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.5,
    cutoffECP: 65,
  },
  {
    id: 'eth',
    name: 'ETH Zurich',
    country: 'Switzerland',
    ranking: 10,
    avgFees: 36000,
    program: 'Engineering',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.5,
    cutoffECP: 62,
  },

  // Mid Range - Medium ECP Required
  {
    id: 'uchicago',
    name: 'University of Chicago',
    country: 'USA',
    ranking: 11,
    avgFees: 58000,
    program: 'Business & Economics',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.5,
    cutoffECP: 60,
  },
  {
    id: 'upenn',
    name: 'University of Pennsylvania',
    country: 'USA',
    ranking: 12,
    avgFees: 57000,
    program: 'Business School',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.5,
    cutoffECP: 60,
  },
  {
    id: 'yale',
    name: 'Yale University',
    country: 'USA',
    ranking: 13,
    avgFees: 56000,
    program: 'Liberal Arts',
    fundingAvailable: 'Full',
    cutoffCGPA: 3.7,
    cutoffECP: 70,
  },
  {
    id: 'lse',
    name: 'London School of Economics',
    country: 'UK',
    ranking: 14,
    avgFees: 40000,
    program: 'Economics & Finance',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.4,
    cutoffECP: 58,
  },
  {
    id: 'nyu',
    name: 'New York University',
    country: 'USA',
    ranking: 15,
    avgFees: 55000,
    program: 'Technology & Business',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.3,
    cutoffECP: 55,
  },

  // Accessible Tier - Lower ECP Required
  {
    id: 'utoronto',
    name: 'University of Toronto',
    country: 'Canada',
    ranking: 20,
    avgFees: 35000,
    program: 'Engineering & CS',
    fundingAvailable: 'Partial',
    cutoffCGPA: 3.2,
    cutoffECP: 50,
  },
  {
    id: 'ubc',
    name: 'University of British Columbia',
    country: 'Canada',
    ranking: 25,
    avgFees: 32000,
    program: 'Science & Engineering',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.0,
    cutoffECP: 45,
  },
  {
    id: 'melbourne',
    name: 'University of Melbourne',
    country: 'Australia',
    ranking: 30,
    avgFees: 38000,
    program: 'Engineering & Business',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.0,
    cutoffECP: 45,
  },
  {
    id: 'nus',
    name: 'National University of Singapore',
    country: 'Singapore',
    ranking: 35,
    avgFees: 30000,
    program: 'Engineering & Computer Science',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.1,
    cutoffECP: 48,
  },
  {
    id: 'hkust',
    name: 'HKUST',
    country: 'Hong Kong',
    ranking: 40,
    avgFees: 32000,
    program: 'Technology & Business',
    fundingAvailable: 'Limited',
    cutoffCGPA: 3.0,
    cutoffECP: 45,
  },
]

export const LOAN_OFFERS: LoanOffer[] = [
  {
    id: 'avanse',
    provider: 'Avanse',
    minAmount: 50000,
    maxAmount: 500000,
    interestRate: 9.5,
    processingFee: 1.5,
    tenure: 15,
    ecpRequirement: 60,
    features: ['No collateral', 'Flexible repayment', 'Fast approval', 'Co-applicant supported'],
    locked: false,
  },
  {
    id: 'incred',
    provider: 'InCred',
    minAmount: 50000,
    maxAmount: 750000,
    interestRate: 8.9,
    processingFee: 1.2,
    tenure: 15,
    ecpRequirement: 60,
    features: ['Quick disbursal', 'Mentorship program', 'Career support', 'Insurance included'],
    locked: false,
  },
  {
    id: 'hdfc',
    provider: 'HDFC Bank',
    minAmount: 100000,
    maxAmount: 1000000,
    interestRate: 8.5,
    processingFee: 1.0,
    tenure: 15,
    ecpRequirement: 60,
    features: ['Established reputation', 'Multiple repayment options', 'Insurance coverage', 'Moratorium period'],
    locked: false,
  },
  {
    id: 'axis',
    provider: 'Axis Bank',
    minAmount: 75000,
    maxAmount: 750000,
    interestRate: 9.0,
    processingFee: 1.1,
    tenure: 15,
    ecpRequirement: 55,
    features: ['Quick processing', 'Education grants', 'Career guidance', 'Alumni network'],
    locked: false,
  },
  {
    id: 'icici',
    provider: 'ICICI Bank',
    minAmount: 80000,
    maxAmount: 800000,
    interestRate: 8.75,
    processingFee: 1.25,
    tenure: 15,
    ecpRequirement: 55,
    features: ['Competitive rates', 'Flexible terms', 'Part-time job assistance', 'Placement support'],
    locked: false,
  },
]

export const ECP_QUESTIONS = [
  {
    id: 'q1',
    question: 'Current CGPA/Percentage (out of 10)?',
    hint: 'Your academic performance',
    scale: 10,
  },
  {
    id: 'q2',
    question: 'Standardized Test Score (GMAT/GRE/GATE)?',
    hint: 'Score on a scale of 100',
    scale: 100,
  },
  {
    id: 'q3',
    question: 'Work Experience (in years)?',
    hint: 'Total years of professional experience',
    scale: 20,
  },
  {
    id: 'q4',
    question: 'Number of Internships/Practical Training?',
    hint: 'Count of relevant internships',
    scale: 10,
  },
  {
    id: 'q5',
    question: 'Projects/Publications/Patents?',
    hint: 'Academic and professional projects',
    scale: 15,
  },
  {
    id: 'q6',
    question: 'Leadership & Extracurricular Roles?',
    hint: 'Leadership positions held',
    scale: 10,
  },
  {
    id: 'q7',
    question: 'Language Proficiency (IELTS/TOEFL)?',
    hint: 'English proficiency score',
    scale: 120,
  },
  {
    id: 'q8',
    question: 'Additional Certifications/Courses?',
    hint: 'Relevant online courses and certifications',
    scale: 20,
  },
]
